### ISSUE TITLE
Add videos/talks section

### ISSUE THREAD

**Issue by tiaanduplessis** [RyanZim/awesome-npm-scripts#10]
How would you feel about adding a videos/talks section to the list? I think talks like [this one](https://www.youtube.com/watch?v=0RYETb9YVrk) may be very useful.

**Comment by RyanZim** [comment]
@mightyCrow I'd be open to that. :+1:  I'll try to take a look at that talk when I get to it.

**Comment by RyanZim** [comment]
@mightyCrow Finally got to look at it; PR welcome.

If you can find a few more, that would be great!

Thanks for all your help! If you get time: https://github.com/RyanZim/awesome-npm-scripts/issues/9.

**Comment by tiaanduplessis** [comment]
@RyanZim Awesome! Will create the PR & checkout #9 as soon as I have time. 👍

**Comment by tiaanduplessis** [comment]
@RyanZim where in the contents would you like me to add the videos section?

**Comment by RyanZim** [comment]
@mightyCrow I would add the section right below **Articles**. Run `npm run doctoc` to regenerate the TOC.

**Comment by tiaanduplessis** [comment]
#11
