### ISSUE TITLE
add live-server

### ISSUE THREAD

**Issue by maxlath** [RyanZim/awesome-npm-scripts#2]
Not sure in which category to put it, but [live-server](https://github.com/tapio/live-server) is easily in my top 5 npm scripts utilities. Typically used to develop minimalist static pages lacking their own live-reloading servers like Github Pages. [example](https://github.com/inventaire/stack/blob/master/package.json#L7)

**Comment by RyanZim** [comment]
Yeah, I've used that in the past too, just somehow forgot to put it on the list. Thanks for bringing this up!

PR welcome, make a new "Dev Servers" category. Could also include https://github.com/indexzero/http-server for when you don't want/need live reloading.
