### ISSUE TITLE
Possible Additions

### ISSUE THREAD

**Issue by RyanZim** [RyanZim/awesome-npm-scripts#9]
These are some possible additions to this list; various things I have found but never tried. They look awesome, but I can't know for sure until I try them.

If you have used any of the tools on this list, please comment about your experience (good or bad) below. If you've had a good experience, I will probably add it to the list.
- https://github.com/srph/npm-scripts-info
- https://github.com/bahmutov/grunty
- ~~https://github.com/heldr/headr~~
- ~~https://github.com/substack/catw~~
- ~~https://github.com/stefanmaric/ntee~~

**Comment by RyanZim** [comment]
Added https://github.com/stefanmaric/ntee

**Comment by tiaanduplessis** [comment]
https://github.com/srph/npm-scripts-info looks interesting. Will try it out soon..

**Comment by RyanZim** [comment]
Added https://github.com/substack/catw

**Comment by RyanZim** [comment]
@tiaanduplessis Did you get a chance to try that?

Also, perhaps you want to try https://github.com/RyanZim/edit-script. Of course, I think it's good (because I wrote it), but would like someone else's thoughts on it.

**Comment by RyanZim** [comment]
@tiaanduplessis ping?

**Comment by RyanZim** [comment]
Added https://github.com/heldr/headr.

**Comment by RyanZim** [comment]
Closing as the remaining two projects seem to be unmaintained.
